### PR TITLE
EN-36489 Add support to send raw messages.

### PR DESCRIPTION
**Pull request by chitang**
This facilitates adding missing rows_loaded metric support in NBE.

### CODE REVIEW

**Comment by rjmac** [comment]
What are you trying to do here?  This doesn't look like you want to use Eurybates at all, you just want to send an AMQ message.

**Comment by chitang** [comment]
For sending both Eurybates and non-Eurybates messages without setting up two separate systems.

**Comment by rjmac** [comment]
Just set up the second system.  Eurybates isn't an AMQ library, it's a messaging library that can be set up to be backed by AMQ or Kafka.

**Comment by rjmac** [comment]
Or just re-use the existing connection that's used to set up the AMQ eurybates backend in the first place.

**Pull request closed without merging**
